apiVersion: v1
kind: Config
clusters:
  - name: board-cluster
    cluster:
      server: https://192.100.1.10:32639
      certificate-authority-data: REPLACE_WITH_BASE64_CA_CRT
contexts:
  - name: board-context
    context:
      cluster: board-cluster
      user: jenkins-user
      namespace: chw
current-context: board-context
users:
  - name: jenkins-user
    user:
      token: REPLACE_WITH_K8S_SERVICE_ACCOUNT_TOKEN
